apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
  - name: PostgreSQL
    type: postgres
    url: finshield-postgres:5432
    database: finshield
    user: admin
    secureJsonData:
      password: CHANGE_ME_postgres_password
    jsonData:
      sslmode: disable
